### ISSUE TITLE
System.InvalidOperationException: Not configured @ ...Configuration.ConfigurationManager.LoadSettings()

### ISSUE THREAD

**Issue by jwalters-gpsw** [actions-runner-controller/actions-runner-controller#458]
I'm seeing the failure seen at the end of log in this [problem report](https://github.com/microsoft/azure-pipelines-agent/issues/2632): https://github.com/microsoft/azure-pipelines-agent/issues/2632

I installed the helm chart: `actions-runner-controller-0.8.0` on 3/11/2021.

I looked on the pod(s) and did not see the credential files. The runners always work fine for awhile but eventually get into this state (after roughly 1-8 hours) where they fail with the log errors in the above problem report.

Do I need a new version of the controller? Your runner docker image? Runner?

**Comment by jwalters-gpsw** [comment]
> I'm seeing the failure seen at the end of log in this [problem report](https://github.com/microsoft/azure-pipelines-agent/issues/2632): [microsoft/azure-pipelines-agent#2632](https://github.com/microsoft/azure-pipelines-agent/issues/2632)
> 
> I installed the helm chart: `actions-runner-controller-0.8.0` on 3/11/2021.
> 
> I looked on the pod(s) and did not see the credential files. The runners always work fine for awhile but eventually get into this state (after roughly 1-8 hours) where they fail with the log errors in the above problem report.
> 
> Do I need a new version of the controller? Your runner docker image? Runner?

In case that link doesn't work, this is the failure lines:

```
[2019-11-26 18:21:00Z ERR  AgentProcess] System.InvalidOperationException: Not configured
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.LoadSettings()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by mumoshu** [comment]
@jwalters-gpsw Hey! I have literally no expertise on the internals of the runner as I'm not a folk from Azure or GitHub. But a quick look on the linked issue makes me think that your runner is too outdated and itw as unable to auto-update.

**Comment by jwalters-gpsw** [comment]
> @jwalters-gpsw Hey! I have literally no expertise on the internals of the runner as I'm not a folk from Azure or GitHub. But a quick look on the linked issue makes me think that your runner is too outdated and itw as unable to auto-update.

That's what I was thinking. I see I'm on an older version of the helm chart. So I'm going to upgrade that. If I still see the problem (which I doubt) I might see if I can get the `--once `option to actually terminate the pod. I would rather than a "clean" environment from a pod recreation. Thanks!

**Comment by jwalters-gpsw** [comment]
> > @jwalters-gpsw Hey! I have literally no expertise on the internals of the runner as I'm not a folk from Azure or GitHub. But a quick look on the linked issue makes me think that your runner is too outdated and itw as unable to auto-update.
> 
> That's what I was thinking. I see I'm on an older version of the helm chart. So I'm going to upgrade that. If I still see the problem (which I doubt) I might see if I can get the `--once `option to actually terminate the pod. I would rather than a "clean" environment from a pod recreation. Thanks!

I updated the controller/runnerdeployments. I'll follow up next week with whether the issue is resolved.

**Comment by jwalters-gpsw** [comment]
Have not seen issue since updating the components. Closing.

**Comment by jwalters-gpsw** [comment]
Actually, this is still occurring. I'll see if I can understand the circumstances better.

**Comment by mumoshu** [comment]
@jwalters-gpsw What was your controller version? 0.18.2?

**Comment by mumoshu** [comment]
@jwalters-gpsw Also, could you move all your comments made in #466 to this thread? #466 is a totally different issue.

**Comment by mumoshu** [comment]
Well, moving those myself.

---

@jwalters-gpsw wrote:

> I'm still [dealing](https://github.com/summerwind/actions-runner-controller/issues/458) with the credentials not being set when the runner "runs". But I could easily hack around the situation if I could set a liveness probe (exec) in my RunnerDeployment. There is both characteristic text in the log file as well as missing files in the /runner directory. Is that possible?

@mumoshu wrote:

> @jwalters-gpsw Hey! Stil trying to understand your issue, but isn't that different from what we're talking here? Are you seeing `lost communication with the server` message?

**Comment by mumoshu** [comment]
@jwalters-gpsw How's your runner shown in the GitHub Web UI when it failed with the not-configured error? `offline`?

**Comment by mumoshu** [comment]
Anyway' we've fixed a bunch of things related to runner not reliably coming up. You'd have better experience with the latest controller image of 0.18.2. Note that chart version and controller version are totally different. You'd better use the latest chart and the latest controller image. Do not try to use the latest controller image with an older chart :)

**Comment by jwalters-gpsw** [comment]
> @jwalters-gpsw How's your runner shown in the GitHub Web UI when it failed with the not-configured error? `offline`?

Sorry for the delay. Yes, offline. Still occurring. What chart version should I use. My current chart is: actions-runner-controller-0.10.5.

**Comment by jwalters-gpsw** [comment]
> > @jwalters-gpsw How's your runner shown in the GitHub Web UI when it failed with the not-configured error? `offline`?
> 
> Sorry for the delay. Yes, offline. Still occurring. What chart version should I use. My current chart is: actions-runner-controller-0.10.5.

Also, your helm repo seems to be down.

**Comment by callum-tait-pbx** [comment]
> Also, your helm repo seems to be down.

The project recently transfered owner, are you still configured for the old owner?

**Comment by jwalters-gpsw** [comment]
> > Also, your helm repo seems to be down.
> 
> @jwalters-gpsw The project recently transfered owner, are you still configured for the old owner?

Ah. Thanlks. That is the issue.

**Comment by mumoshu** [comment]
@jwalters-gpsw I that case you could just try upgrading your helm release to use 0.11.0. The chart 0.11.0 defaults to using actions-runner-controller 0.18.2.

https://github.com/actions-runner-controller/actions-runner-controller/commit/3b2d2c052eb843cd7f1509960681d501c81f8eab

**Comment by jwalters-gpsw** [comment]
Seems to be stable now. Consistently getting the .`credentials`. Closing this.
